-- Copies the value of each data point to its label

local enum = require("tng.config").enum

return {
	id = "copy-value-to-label",
	version = "1.0.1",
	inputCount = 1,
	categories = { "_transform" },
	title = {
		["en"] = "Copy Value to Label",
		["af"] = "Kopieer Waarde na Etiket",
		["sq"] = "Kopjo vlerën te etiketa",
		["am"] = "ዋጋን ወደ መለያ ቅዳ",
		["hy"] = "Արժեքը պատճենել պիտակում",
		["az"] = "Qiyməti etiketə köçür",
		["bn"] = "লেবেলে মান কপি করুন",
		["eu"] = "Kopiatu balioa etiketara",
		["be"] = "Скапіяваць значэнне ў ярлык",
		["bg"] = "Копиране на стойността в етикета",
		["my"] = "တန်ဖိုးကို အညွှန်းသို့ ကူးယူရန်",
		["ca"] = "Copia el valor a l’etiqueta",
		["zh-Hans"] = "将值复制到标签",
		["zh-Hant"] = "將值複製到標籤",
		["hr"] = "Kopiraj vrijednost u oznaku",
		["cs"] = "Kopírovat hodnotu do štítku",
		["da"] = "Kopiér værdi til etiket",
		["nl"] = "Waarde naar label kopiëren",
		["et"] = "Kopeeri väärtus sildiks",
		["fil"] = "Kopyahin ang Halaga sa Label",
		["fi"] = "Kopioi arvo selitteeseen",
		["fr"] = "Copier la valeur dans le libellé",
		["gl"] = "Copiar o valor na etiqueta",
		["ka"] = "მნიშვნელობის იარლიყში კოპირება",
		["de"] = "Wert in Label kopieren",
		["el"] = "Αντιγραφή τιμής στην ετικέτα",
		["gu"] = "મૂલ્યને લેબલમાં કૉપી કરો",
		["hi"] = "मान को लेबल में कॉपी करें",
		["hu"] = "Érték másolása címkébe",
		["is"] = "Afrita gildi í merki",
		["id"] = "Salin Nilai ke Label",
		["it"] = "Copia valore nell'etichetta",
		["ja"] = "値をラベルにコピー",
		["kn"] = "ಮೌಲ್ಯವನ್ನು ಲೇಬಲ್‌ಗೆ ನಕಲಿಸಿ",
		["kk"] = "Мәнді жапсырмаға көшіру",
		["km"] = "ចម្លងតម្លៃទៅស្លាក",
		["ko"] = "값을 라벨에 복사",
		["ky"] = "Маанини энбелгиге көчүрүү",
		["lo"] = "ຄັດລອກຄ່າໄປໃສ່ປ້າຍ",
		["lv"] = "Kopēt vērtību uz etiķeti",
		["lt"] = "Kopijuoti reikšmę į etiketę",
		["mk"] = "Копирај ја вредноста во ознаката",
		["ms"] = "Salin Nilai ke Label",
		["ml"] = "മൂല്യം ലേബലിലേക്ക് പകർത്തുക",
		["mr"] = "मूल्य लेबलमध्ये कॉपी करा",
		["mn"] = "Утгыг шошго руу хуулах",
		["ne"] = "मानलाई लेबलमा प्रतिलिपि गर्नुहोस्",
		["no"] = "Kopier verdi til etikett",
		["pl"] = "Kopiuj wartość do etykiety",
		["pt"] = "Copiar valor para o rótulo",
		["pa"] = "ਮੁੱਲ ਨੂੰ ਲੇਬਲ ਵਿੱਚ ਕਾਪੀ ਕਰੋ",
		["ro"] = "Copiază valoarea în etichetă",
		["rm"] = "Copiar la valur en l’etichetta",
		["ru"] = "Копировать значение в метку",
		["sr"] = "Kopiraj vrednost u oznaku",
		["si"] = "අගය ලේබලයට පිටපත් කරන්න",
		["sk"] = "Kopírovať hodnotu do označenia",
		["sl"] = "Kopiraj vrednost v oznako",
		["es"] = "Copiar valor en etiqueta",
		["sw"] = "Nakili Thamani kwenye Lebo",
		["sv"] = "Kopiera värde till etikett",
		["ta"] = "மதிப்பை லேபிளுக்கு நகலெடு",
		["te"] = "విలువను లేబుల్‌కు కాపీ చేయి",
		["th"] = "คัดลอกค่าไปยังป้ายกำกับ",
		["tr"] = "Değeri Etikete Kopyala",
		["uk"] = "Копіювати значення в мітку",
		["vi"] = "Sao chép giá trị vào nhãn",
	},
	description = {
		["en"] = "Copies each data point's value to its label as a string.",
		["af"] = "Kopieer elke datapunt se waarde as ’n string na sy etiket.",
		["sq"] = "Kopjon vlerën e çdo pike të të dhënave te etiketa e saj si varg teksti.",
		["am"] = "የእያንዳንዱን የውሂብ ነጥብ ዋጋ እንደ ጽሑፍ ወደ መለያው ይቀዳል።",
		["hy"] = "Յուրաքանչյուր տվյալակետի արժեքը որպես տող պատճենում է դրա պիտակում։",
		["az"] = "Hər məlumat nöqtəsinin qiymətini mətn kimi onun etiketinə köçürür.",
		["bn"] = "প্রতিটি ডেটা পয়েন্টের মানকে একটি স্ট্রিং হিসেবে তার লেবেলে কপি করে।",
		["eu"] = "Datu-puntu bakoitzaren balioa etiketan kopiatzen du, kate gisa.",
		["be"] = "Капіруе значэнне кожнай кропкі даных у яе ярлык як радок.",
		["bg"] = "Копира стойността на всяка точка от данни в нейния етикет като текст.",
		["my"] = "ဒေတာမှတ်တစ်ခုချင်းစီ၏ တန်ဖိုးကို စာသားအဖြစ် ၎င်း၏အညွှန်းသို့ ကူးယူသည်။",
		["ca"] = "Copia el valor de cada punt de dades a la seva etiqueta com a cadena de text.",
		["zh-Hans"] = "将每个数据点的值作为字符串复制到其标签中。",
		["zh-Hant"] = "將每個資料點的值以字串形式複製到其標籤。",
		["hr"] = "Kopira vrijednost svake podatkovne točke u njezinu oznaku kao niz znakova.",
		["cs"] = "Zkopíruje hodnotu každého datového bodu do jeho štítku jako řetězec.",
		["da"] = "Kopierer hvert datapunkts værdi til dets etiket som en streng.",
		["nl"] = "Kopieert de waarde van elk gegevenspunt als tekst naar het label.",
		["et"] = "Kopeerib iga andmepunkti väärtuse tekstina selle sildiks.",
		["fil"] = "Kinokopya ang halaga ng bawat data point sa label nito bilang string.",
		["fi"] = "Kopioi kunkin datapisteen arvon selitteeseen merkkijonona.",
		["fr"] = "Copie la valeur de chaque point de données dans son libellé sous forme de chaîne.",
		["gl"] = "Copia o valor de cada punto de datos na súa etiqueta como texto.",
		["ka"] = "თითოეული მონაცემის წერტილის მნიშვნელობას სტრიქონის სახით მის იარლიყში აკოპირებს.",
		["de"] = "Kopiert den Wert jedes Datenpunkts als Zeichenfolge in dessen Label.",
		["el"] = "Αντιγράφει την τιμή κάθε σημείου δεδομένων στην ετικέτα του ως συμβολοσειρά.",
		["gu"] = "દરેક ડેટા પોઇન્ટના મૂલ્યને સ્ટ્રિંગ તરીકે તેના લેબલમાં કૉપી કરે છે.",
		["hi"] = "हर डेटा पॉइंट के मान को स्ट्रिंग के रूप में उसके लेबल में कॉपी करता है।",
		["hu"] = "Az egyes adatpontok értékét szövegként a címkéjükbe másolja.",
		["is"] = "Afritar gildi hvers gagnapunkts í merki þess sem texta.",
		["id"] = "Menyalin nilai setiap titik data ke labelnya sebagai string.",
		["it"] = "Copia il valore di ogni punto dati nell'etichetta come stringa.",
		["ja"] = "各データポイントの値を文字列としてラベルにコピーします。",
		["kn"] = "ಪ್ರತಿ ಡೇಟಾ ಬಿಂದುವಿನ ಮೌಲ್ಯವನ್ನು ಸ್ಟ್ರಿಂಗ್ ಆಗಿ ಅದರ ಲೇಬಲ್‌ಗೆ ನಕಲಿಸುತ್ತದೆ.",
		["kk"] = "Әр дерек нүктесінің мәнін жол ретінде оның жапсырмасына көшіреді.",
		["km"] = "ចម្លងតម្លៃរបស់ចំណុចទិន្នន័យនីមួយៗទៅស្លាករបស់វាជាខ្សែអក្សរ។",
		["ko"] = "각 데이터 포인트의 값을 문자열로 변환하여 라벨에 복사합니다.",
		["ky"] = "Ар бир маалымат чекитинин маанисин сап катары анын энбелгисине көчүрөт.",
		["lo"] = "ຄັດລອກຄ່າຂອງຈຸດຂໍ້ມູນແຕ່ລະຈຸດໄປໃສ່ປ້າຍຂອງມັນໃນຮູບແບບສະຕຣິງ.",
		["lv"] = "Kopē katra datu punkta vērtību tā etiķetē kā virkni.",
		["lt"] = "Kiekvieno duomenų taško reikšmę nukopijuoja į jo etiketę kaip eilutę.",
		["mk"] = "Ја копира вредноста на секоја точка на податоци во нејзината ознака како текст.",
		["ms"] = "Menyalin nilai setiap titik data ke labelnya sebagai rentetan.",
		["ml"] = "ഓരോ ഡാറ്റാ പോയിന്റിന്റെയും മൂല്യം ഒരു സ്ട്രിംഗായി അതിന്റെ ലേബലിലേക്ക് പകർത്തുന്നു.",
		["mr"] = "प्रत्येक डेटा बिंदूचे मूल्य स्ट्रिंग म्हणून त्याच्या लेबलमध्ये कॉपी करते.",
		["mn"] = "Өгөгдлийн цэг бүрийн утгыг тэмдэгт мөр хэлбэрээр шошгонд нь хуулна.",
		["ne"] = "प्रत्येक डेटा बिन्दुको मानलाई स्ट्रिङका रूपमा यसको लेबलमा प्रतिलिपि गर्छ।",
		["no"] = "Kopierer verdien til hvert datapunkt til etiketten som en tekststreng.",
		["pl"] = "Kopiuje wartość każdego punktu danych do jego etykiety jako tekst.",
		["pt"] = "Copia o valor de cada ponto de dados para o respetivo rótulo como texto.",
		["pa"] = "ਹਰੇਕ ਡਾਟਾ ਪੁਆਇੰਟ ਦੇ ਮੁੱਲ ਨੂੰ ਸਤਰ ਵਜੋਂ ਉਸਦੇ ਲੇਬਲ ਵਿੱਚ ਕਾਪੀ ਕਰਦਾ ਹੈ।",
		["ro"] = "Copiază valoarea fiecărui punct de date în eticheta sa sub formă de șir de caractere.",
		["rm"] = "Copia la valur da mintga punct da datas en sia etichetta sco stringa.",
		["ru"] = "Копирует значение каждой точки данных в её метку в виде строки.",
		["sr"] = "Kopira vrednost svake tačke podataka u njenu oznaku kao tekst.",
		["si"] = "සෑම දත්ත ලක්ෂ්‍යයකම අගය පෙළක් ලෙස එහි ලේබලයට පිටපත් කරයි.",
		["sk"] = "Skopíruje hodnotu každého údajového bodu do jeho označenia ako reťazec.",
		["sl"] = "Kopira vrednost vsake podatkovne točke v njeno oznako kot niz.",
		["es"] = "Copia el valor de cada punto de datos en su etiqueta como texto.",
		["sw"] = "Hunakili thamani ya kila nukta ya data kwenye lebo yake kama maandishi.",
		["sv"] = "Kopierar varje datapunkts värde till dess etikett som en sträng.",
		["ta"] = "ஒவ்வொரு தரவுப் புள்ளியின் மதிப்பையும் சரமாக அதன் லேபிளுக்கு நகலெடுக்கிறது.",
		["te"] = "ప్రతి డేటా పాయింట్ విలువను స్ట్రింగ్‌గా దాని లేబుల్‌కు కాపీ చేస్తుంది.",
		["th"] = "คัดลอกค่าของจุดข้อมูลแต่ละจุดไปยังป้ายกำกับในรูปแบบสตริง",
		["tr"] = "Her veri noktasının değerini dize olarak etiketine kopyalar.",
		["uk"] = "Копіює значення кожної точки даних у її мітку як рядок.",
		["vi"] = "Sao chép giá trị của mỗi điểm dữ liệu vào nhãn dưới dạng chuỗi.",
	},
	config = {
		enum {
			id = "mode",
			name = "_mode",
			options = {
				"_overwrite",
				"_prepend",
				"_append",
			},
			default = "_overwrite",
		},
	},

	generator = function(source, config)
		local mode = config and config.mode or "_overwrite"

		return function()
			local data_point = source.dp()
			if not data_point then
				return nil
			end

			local value_str = tostring(data_point.value)
			local existing = data_point.label or ""

			if mode == "_overwrite" then
				data_point.label = value_str
			elseif mode == "_prepend" then
				data_point.label = value_str .. existing
			elseif mode == "_append" then
				data_point.label = existing .. value_str
			end

			return data_point
		end
	end,
}
