/*
 *  This file is part of Track & Graph
 *
 *  Track & Graph is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Track & Graph is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Track & Graph.  If not, see <https://www.gnu.org/licenses/>.
 */
// Generated by scripts/translations/generate_playstore_screenshot_tests.py. Do not edit.
package com.samco.trackandgraph.playstore

import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview
import com.android.tools.screenshot.PreviewTest

private const val PLAY_STORE_DEVICE = "spec:width=1080px,height=2340px,dpi=420"

@Target(AnnotationTarget.FUNCTION, AnnotationTarget.ANNOTATION_CLASS)
@Retention(AnnotationRetention.BINARY)
@Preview(name = "en", locale = "en", device = PLAY_STORE_DEVICE)
@Preview(name = "de", locale = "de-rDE", device = PLAY_STORE_DEVICE)
@Preview(name = "es", locale = "es", device = PLAY_STORE_DEVICE)
@Preview(name = "fr", locale = "fr", device = PLAY_STORE_DEVICE)
private annotation class PlayStoreLocalesPreview

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot01() {
    PlayStoreDailyGroupScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot02() {
    PlayStoreExerciseScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot03() {
    PlayStoreDailyAddStressScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot04() {
    PlayStoreDailyDarkScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot05() {
    PlayStoreRestDayStatisticsScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot06() {
    PlayStoreFlexibleOrganisationScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot07() {
    PlayStoreRemindersScreenshotContent()
}

@PreviewTest
@PlayStoreLocalesPreview
@Composable
fun PlayStoreScreenshot08() {
    PlayStoreFunctionEditorScreenshotContent()
}
