return {
  running_min_aggregator = 3,
  running_max_aggregator = 3,
  simple_min_aggregator = 3,
  simple_max_aggregator = 3,
  avg_aggregator = 3,
  sum_aggregator = 3,
  variance_aggregator = 3,
  stdev_aggregator = 3,
  count_aggregator = 3,

  running_min_aggregator2 = 4,
  running_max_aggregator2 = 4,
  simple_min_aggregator2 = 4,
  simple_max_aggregator2 = 4,
  avg_aggregator2 = 4,
  sum_aggregator2 = 4,
  variance_aggregator2 = 4,
  stdev_aggregator2 = 4,
  count_aggregator2 = 4,
}
